export interface initialTicketDetails {
    id: string,
    created: string,
    lastmessage: string,
    status: string[],
    rating: string,
    priority: string[],
    source: string,
    language: string,
    tags: string,
    addtag: string,
    custom: string[],
    archive: string,
    similartickets: string[],
}